mongo_uri: ENC[AES256_GCM,data:gnWIUI8lnb580zYp8w/c77B+x3nBahCbyhl0MKjxOTBEPqxR/KIvVsQ5ACUW/1q11K1XXWz811p+JPQ6Dwwez+lJgqC8Pn+FAUGjBV6MGUwDEdGskeMCoOddQzCg6wyWsKv5KS0J+CAhAGC2uLnCyWr+8SdVSfc=,iv:aS0VTgbAeg0DwHEfk7QXWSkiaEsyNCXo/I86Uc5IRXo=,tag:VYlKAmXMCkGndkKaOh+P2Q==,type:str]
jwt_secret: ENC[AES256_GCM,data:XvMtjGq6JQBX9Ch0uyZqIjK/1PQ=,iv:iTL+qX9e6MsOXiuEvN5w8doJN8vkjbk1F217GMDJj1o=,tag:FOll7Lng216Y8nVrlQrOFA==,type:str]
sops:
    age:
        - recipient: age1z7fje8ex3nyl05f4e6e4y80klf783ala6gwyjnnt35hevcah2g2qvdutld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRUFk3bUkrTVd3TU1xWTV4
            QnY0Zk5qM3BnaytESVVJVUlrbnh0d0QxY0FzCjFKem1ZbE9qaW9acTJoQ3U3T3JP
            TU9JS1pwRWNXNGlHZEs1dmlwcUkyYTgKLS0tIHBielVtZjFMc2I2YzdqTFNwVUlu
            OGlSSFBPVStuUjNkcWhtVzFKS2x2Rm8K/PgP1n++8US+nufDDPscAl8ZYSpsQ7Qu
            ZSRkuQcG7je3sYKdhWcwa8pqxW/U51t82ng+Lt4xkmAioCARDJZqRQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-05-02T17:43:15Z"
    mac: ENC[AES256_GCM,data:4AYylhJTUi5sFooCi0AZWgs0l0Hx5miAAx+EeX+YEzlneVNooy5c7rY4nA5fTey/xT5HtNg8sTUvMkS7oKsInnXxpaX5CI18Feh29aEzFj91k6q+VUNWyv/tbuLqhinopLgpIV9TRypcRSYBfCUDqADnTBIvn+ZnI/MjEQ8whZ4=,iv:6I49yldMYwqbfv6A9ZuES0cFYKYwRIybu1vvOne64Ak=,tag:Z+fOQNR9Mr4CLlJi5n19AA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
