k3s_token: ENC[AES256_GCM,data:Ihfzc3BRqqfRmfvQO7lqe+mMf3vW/UmVMfNV0N8HVv9ZaXGOnZzP79C/L0U6c1kyFEcEs7fbxdggYnTbc/FMIQ==,iv:p6zmeP/F4X8WldTJxQZfciqJpm1skdr14FHVP0Bl8Uw=,tag:Ulkn3V8C5NhNIUT5Av4i/Q==,type:str]
sops:
    age:
        - recipient: age1z7fje8ex3nyl05f4e6e4y80klf783ala6gwyjnnt35hevcah2g2qvdutld
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzUmdLTnVvaDZONVNWQlpu
            M3haS0FBZGRLcXN2VHNiWTl1NnQrcC9QSUNrCm9ZaGYxaDZPWHEzeVYvRHBLVnla
            Sjc4UCtxN2NHRlJSVU9HU21pdGswK2MKLS0tIFRoRGV6Q01tMTBWQ2ZLeE5XNTFh
            YmJwbndad2hpYlZaYTBQTUFibGNPUmsKPe+GV6XyIuOzqxviNURk9zralkovH0LP
            cdZPifZ7FSkdf6oLrQycudS6cH/pEPMl+S9PXkvQvJiekkv3pneerA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-30T03:26:45Z"
    mac: ENC[AES256_GCM,data:79T9h+dt/PTkVk9wCs4bmuqyp7WCMtAL2NYCf0+ZLqIQZMN/SA8D9383VVF/smq7R3d4viZLypu/9st3UnTVH5p37py9uosZgS4k8sNbAJGfi9oMsrHPXCn0mwO54oZB4nMW1Of+vP4CaDSvw22bZIDsMKH5BEoDYQqAd+OaOcg=,iv:uOGjOlTbkRQ9L4WSOlhaI/wE9R67oGdNsV4hdFZ5g3I=,tag:uFDWLLYguanpfi74h9/d2Q==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.2
